#:kivy 2.0.0
<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size : root.width, root.height

        spacing: 20
        padding: 50

        Button:
            text: "Hello World"

        Button:
            text: "Goodbye World"
        
        Button:
            text: "I'm Hungry"
            size_hint: (.5, .5)
            #width : 200
            #height: 50
            pos_hint: {'center_x' : 0.5}